# Generated by Django 4.0.5 on 2023-08-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0002_sprofile_tprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SProfile',
        ),
        migrations.DeleteModel(
            name='TProfile',
        ),
    ]
