# Generated by Django 4.0.5 on 2023-08-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0004_tprofile_sprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfimg',
            field=models.ImageField(default='demoprofile.png', upload_to='Profiles/'),
        ),
    ]
