# Generated by Django 4.2.5 on 2023-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0006_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='ntfle',
            field=models.FileField(default='static/images/DataFiles/data_1.xlsx', upload_to='DataFiles'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='year',
            field=models.CharField(choices=[('0', 'Select Product'), ('1', 'Milk'), ('2', 'Curd'), ('3', 'Cheese'), ('4', 'Panner'), ('5', 'Badam Milk')], default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='sprofile',
            name='year',
            field=models.CharField(choices=[('0', 'Select Product'), ('1', 'Milk'), ('2', 'Curd'), ('3', 'Cheese'), ('4', 'Panner'), ('5', 'Badam Milk')], default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('G', 'Guest'), ('T', 'Merchant'), ('S', 'Customer'), ('D', 'Doctor')], default='G', max_length=5),
        ),
    ]
